include $(HOME)/Makefiles/common.mk

LIBS := libcircul
OBJS_libcircul := circul

EXES := cirtail uncircular
LIBS_cirtail := libcircul
LARGS_cirtail := -lm
LIBS_uncircular := libcircul
LARGS_uncircular := -lm

include $(TEMPLATES)/c.mk

