include $(HOME)/Makefiles/common.mk

LIBS := libcircul
OBJS_libcircul := circul

EXES := cirtail uncircular cirpipe
LIBS_cirtail := libcircul
LARGS_cirtail := -lm
LIBS_uncircular := libcircul
LARGS_uncircular := -lm
LIBS_cirpipe := libcircul
LARGS_cirpipe := -lm

include $(TEMPLATES)/c.mk

