include $(HOME)/Makefiles/common.mk

DINCL := boolean
DLIBA := timeval

FILES2LINK := wait_evt.h wait_evt.c
LINKFROM := $(HOME)/ada/c

LIBS := libwait_evt

OBJS_libwait_evt := wait_evt.o

include $(TEMPLATES)/c.mk

