include $(HOME)/Makefiles/common.mk

LIBS := libmodule1 libmodule2
OBJS_libmodule1 := module1
OBJS_libmodule2 := module2

EXES := try
LARGS_try := -L$(LIB) -lmodule1 -lmodule2

include $(TEMPLATES)/c.mk

