include $(HOME)/Makefiles/common.mk

BOOLEAN=../boolean

FILES2LINK := timeval.h timeval.c
LINKFROM := $(HOME)/ada/c

LIBS := libtimeval

OBJS_libtimeval := timeval.o
CARGS_timeval := -I$(BOOLEAN)

include $(TEMPLATES)/c.mk

