#!/bin/bash

export pid=$1

function do_one {
  date=`date "+%Y/%m/%d-%H:%M:%S"`
  vsz=`ps u -p $pid | awk '(NR == 2) {print $5}'`
  if [ "$vsz" = ""  ] ; then
    exit 0
  fi
  #let vsz=$vsz/1024
  let vsz=$vsz+0
  if [ $vsz -eq 0 ] ; then
    exit 0
  fi
  echo "$date $vsz"
}


while true ; do
  do_one
  usleep 500000
done

