include $(HOME)/Makefiles/common.mk

LIBS := libadjtime
OBJS_libadjtime := adjtime_call

EXES := adjtime prof_adjtime
LIBS_adjtime := libadjtime
LIBS_prof_adjtime := libadjtime

include $(TEMPLATES)/c.mk

