include $(HOME)/Makefiles/common.mk

LIBS := libadjtime
OBJS_libadjtime := adjtime_call.o

EXES := adjtime prof_adjtime
LIBS_adjtime := libadjtime.a
LIBS_prof_adjtime := libadjtime.a

include $(TEMPLATES)/c.mk

