include $(HOME)/Makefiles/common.mk

DINCL := boolean
DLIBA := socket_evt wait_evt timeval

LIBS := libutil
OBJS_libutil := util.o

EXES := udpspy
LIBS_udpspy := libutil.a

include $(TEMPLATES)/c.mk

